### ISSUE TITLE
enable curators and annotators to 'Reopen' document from the 'Finish' page

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#72] opened 2020-03-19 16:05 UTC
include a button on the 'Finish' page that enables curators and annotators to return the article back to the main annotation screen

**Comment by NicolasKieffer** [comment] 2020-03-23 20:06
In case of "reopened" document, does standard user will be stick on finish page?
(Does only curators & annotators can update "reopened" document?)

**Comment by timvines19** [comment] 2020-03-23 21:57
Reopening a document should move everyone back to the main annotation screen – this enables a workflow like:
authors use DS to share data & click finish -> curator checks finish page, if necessary reopens document & asks authors to share extra data -> authors share extra data & click finish -> curator checks finish page, reopens again if necessary

**Comment by timvines19** [comment] 2020-04-13 22:13
I need this capability to correct the output from Molecular Connections, and other annotators need it too

**Comment by kermitt2** [comment] 2020-04-14 01:11
I am reporting my notes on this regarding the behaviour following roles and how the work can be resumed.

We consider the 3 states:
- `M`: metadata page for an article (metadata of the article to be confirmed)
- `W`: working area with document display and dataset validation tasks
- `F`: final page view after validation of all dataset

* curator can open any documents at any stage, revert state `F` to `W`, and can move to `F` again

* user can access only her/his own document in stage `M` and move to `W`, (s)he can come back at stage `W` as required, then move to `F`. User can also revert back from `F` to `W` (this is new!).

* annotator as similar access possibilities as curator

**Comment by timvines19** [comment] 2020-04-14 23:28
Thanks - this generally looks good. In the dev version, I couldn't (as a user) mover from F back to W because the button was not displaying

![Screen Shot 2020-04-14 at 4 16 13 PM](https://user-images.githubusercontent.com/49563305/79283507-ee6e5f80-7e6c-11ea-9383-7215658bb508.png)

**Comment by kermitt2** [comment] 2020-04-14 23:32
Indeed @timvines19, the `F` to `W` for the user role is something new, not allowed until now, and it need to be implemented.

**Comment by timvines19** [comment] 2020-04-14 23:33
We ought to clarify this as it's a bit ambiguous : 
"curator can open any documents at any stage, revert state F to W, and can move to F again"

-> if the document is at F for a user, it is also at the F stage for a curator [curators should not be able to choose to open a document at F at the W stage instead]

**Comment by kermitt2** [comment] 2020-04-14 23:43
> [curators should not be able to choose to open a document at F at the W stage instead – they would need to use the button to move it from F to W]

Indeed I didn't remember this. The problem is that we also said that curator can move state `W` to `F`... so somehow they need to access state `F` ?

**Comment by timvines19** [comment] 2020-04-14 23:51
If a document is at F, the user, and any of the annotators and curators should be able to access it at F. That's how it is now, which is how I think it should be. Once you've added the 'Reopen Document' button for users, all three user roles will also be able to move it back from F to W

I have a feeling my "we ought to clarify this comment" has just confused things...

**Comment by kermitt2** [comment] 2020-04-15 00:05
No no it's clear !
it's rather me who misunderstood the clarification so I've removed my comment :D

**Comment by timvines19** [comment] 2020-04-15 00:08
Great - once the 'Reopen document' button is available to users (and working!) what would be the timetable for adding this to the Production version?

**Comment by NicolasKieffer** [comment] 2020-04-15 00:30
@kermitt2 I let you check if this is a correct implementation.
Updates are on new branch : _git checkout fix-72-update_

**Comment by kermitt2** [comment] 2020-04-28 15:49
Tested and I think it's all correct.

**Comment by timvines19** [comment] 2020-04-28 16:09
should the 'Reopen document' button be visible for standard_users now? Not seeing it yet.

**Comment by kermitt2** [comment] 2020-04-28 16:40
I've just merged it on master, I will try to deploy it in dev this night (my internet is working better since yesterday, though still unstable), with the line number support.

**Closed** 2020-05-05 16:46 UTC
Labels: Needed for Production version, high priority
