### ISSUE TITLE
Question: can DataSeer use a local version of Grobid?

### ISSUE THREAD

**Issue by timvines19** [kermitt2/dataseer-web#64] opened 2020-03-11 02:03 UTC
Instead of going through the difficult process of updating the global version of Grobid to help it deal with the figure caption issue etc, can we set DataSeer to use a suitably trained local version of Grobid instead?

**Comment by kermitt2** [comment] 2020-03-11 02:27
It does not really change the process - even with a dedicated fork, we still need iteratively to update the training data, the models and to evaluate. The problem is that it would actually make everything more difficult because maintaining several code bases of grobid would imply extra work due to the parallel changes that have to be merged and could conflict.

**Closed** 2020-03-13 19:07 UTC
Labels: question
